#!/data/data/com.termux/files/usr/bin/bash
killall termux-x11 2>/dev/null
rm -rf ~/.cache/xdg-runtime /tmp/.X11-unix/X0

export XDG_RUNTIME_DIR="$HOME/.cache/xdg-runtime"
mkdir -p "$XDG_RUNTIME_DIR" && chmod 700 "$XDG_RUNTIME_DIR"

pulseaudio --start --exit-idle-time=-1 & sleep 2
pactl load-module module-aaudio-sink
pactl set-default-sink "$(pactl list short sinks | grep aaudio | awk '{print $2}')"

termux-x11 :0 & sleep 3
am start -n com.termux.x11/.MainActivity &

export DISPLAY=:0 PULSE_SERVER=$(pactl info | grep "Server String" | cut -d' ' -f3)
startplasma-x11
